[package]
name = "ast-editor"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ast.workspace = true
syntax.workspace = true
schema-store.workspace = true
futures.workspace = true
