[package]
name = "tombi-rg-tree"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
description = "A `Red/Green Tree` implementation."
license.workspace = true

[dependencies]
countme = "3.0.1"
hashbrown = "0.15.0"
itertools.workspace = true
rustc-hash = "2.0.0"
tombi-text.workspace = true

[features]
default = []
