[package]
name = "tombi-lsp"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[[bin]]
name = "tombi-lsp"
path = "src/bin/main.rs"

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
ast.workspace = true
camino = { workspace = true }
clap = { workspace = true, features = ["string"] }
clap-verbosity-flag = { workspace = true }
crossbeam-channel = "0.5.13"
dashmap = "6.1.0"
document = { workspace = true, features = ["lsp"] }
formatter.workspace = true
futures = { workspace = true }
futures-util = { workspace = true }
parser.workspace = true
rustc-hash = { workspace = true }
semver = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
text = { workspace = true, features = ["lsp"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-std", "rt"] }
tower-lsp = { workspace = true}
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
