id = "tombi"
name = "Tombi | TOML Toolkit"
version = "0.1.4"
description = "ðŸ¦…  TOML Language Server  ðŸ¦… "
schema_version = 1
authors = ["tombi-toml <tombi-toml@outlook.com>"]
repository = "https://github.com/tombi-toml/tombi"

[language_servers.toml]
name = "Tombi"
languages = ["TOML"]

[grammars.toml]
repository = "https://github.com/tree-sitter/tree-sitter-toml"
commit = "342d9be207c2dba869b9967124c679b5e6fd0ebe"
