[workspace]
resolver = "2"
members = ["rust/*", "crates/*", "xtask", "toml-test"]

[workspace.package]
version = "0.0.0"  # We use git tags for versioning. This is just a placeholder.
edition = "2021"
authors = ["yassun7010 <yassun7010@outlook.com>"]
license = "MIT"
repository = "https://github.com/yassun7010/tombi"

[workspace.dependencies]
ahash = "0.8.11"
anyhow = "1.0.89"
assert_matches = "1.5.0"
ast = { path = "crates/ast" }
camino = "1.1.9"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive", "string"] }
clap-verbosity-flag = "3.0.1"
config = { path = "crates/config" }
dashmap = "6.1.0"
diagnostic = { path = "crates/diagnostic" }
document = { path = "crates/document" }
document-tree = { path = "crates/document-tree" }
either = "1.13.0"
formatter = { path = "crates/formatter" }
futures = "0.3.31"
futures-util = "0.3.31"
glob = "0.3.1"
indexmap = { version = "2.6.0", features = ["serde"] }
itertools = "0.13.0"
schema-store = { path = "crates/schema-store" }
lexer = { path = "crates/lexer" }
linter = { path = "crates/linter" }
nu-ansi-term = "0.50.1"
parser = { path = "crates/parser" }
pretty_assertions = "1.4.1"
proc-macro2 = "1.0.92"
quote = "1.0.37"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["rustls-tls", "json"] }
rg-tree = { path = "crates/rg-tree" }
rstest = "0.23.0"
rustc-hash = "2.0.0"
schemars = { version = "1.0.0-alpha.17", features = ["preserve_order"] }
semver = "1.0.23"
serde = { version = "^1.0.0", features = ["derive"] }
serde_json = { version = "1.0.130", features = ["preserve_order"] }
server = { path = "crates/server" }
syntax = { path = "crates/syntax" }
text = { path = "crates/text" }
textwrap = "0.16.1"
thiserror = "2.0.3"
tokio = { version = "1.41.0", features = ["fs", "io-std", "rt-multi-thread"] }
toml = "0.8.19"
toml-version = { path = "crates/toml-version" }
tower-lsp = "0.20.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
