[workspace]
resolver = "2"
members = ["rust/*", "crates/*", "xtask"]

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["yassun7010 <yassun7010@outlook.com>"]
license = "MIT"
repository = "https://github.com/yassun7010/tombi"

[workspace.dependencies]
anyhow = "1.0.89"
assert_matches = "1.5.0"
ast = { path = "crates/ast" }
camino = "1.1.9"
clap = { version = "4.5.20", features = ["derive"] }
clap-verbosity-flag = "2.2.2"
diagnostic = { path = "crates/diagnostic" }
document = { path = "crates/document" }
either = "1.13.0"
formatter = { path = "crates/formatter" }
futures = "0.3.31"
futures-util = "0.3.31"
indexmap = "2.6.0"
itertools = "0.13.0"
linter = { path = "crates/linter" }
nu-ansi-term = "0.50.1"
parser = { path = "crates/parser" }
proc-macro2 = "1.0.87"
quote = "1.0.37"
regex = "1.11.1"
rg-tree = { path = "crates/rg-tree" }
rstest = "0.23.0"
rustc-hash = "2.0.0"
schemars = "0.8.21"
semver = "1.0.23"
serde = { version = "^1.0.0", features = ["derive"] }
serde_json = "1.0.130"
syntax = { path = "crates/syntax" }
text = { path = "crates/text" }
textwrap = "0.16.1"
thiserror = "1.0.64"
tokio = "1.41.0"
tower-lsp = "0.20.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
