# Tombi config for this project.
#
# This file is for checking if the JsonSchema is correct.
#

toml-version = "v1.0.0"
exclude = ["node_modules/**/*"]

[format]

[lint]
[lint.rules]
key-empty = "warn"

[lsp]
document-link = { enabled = true }

[schema]
enabled = true
catalog = { path = "https://www.schemastore.org/api/json/catalog.json" }

[[schemas]]
path = "tombi.schema.json"
include = ["tombi.toml"]

[[schemas]]
path = "schemas/cargo.schema.json"
include = ["Cargo.toml"]

[[schemas]]
path = "schemas/pyproject.schema.json"
include = ["pyproject.toml"]

[[schemas]]
path = "schemas/type-test.schema.json"
include = ["type-test.toml"]

[[schemas]]
root = "tool.taskipy"
path = "schemas/partial-taskipy.schema.json"
include = ["pyproject.toml"]
