[package]
name = "ast"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
syntax.workspace = true
text = { workspace = true }
itertools = { workspace = true }
