[package]
name = "tombi-x-keyword"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

[features]
clap = ["dep:clap"]
default = ["clap", "serde"]
jsonschema = ["dep:schemars"]
serde = ["dep:serde"]
