[package]
name = "tombi-document"
version = "0.0.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
chrono = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tombi-ast = { workspace = true }
tombi-date-time = { workspace = true }
tombi-document-tree = { workspace = true }
tombi-parser = { workspace = true }
tombi-text = { workspace = true }
tombi-toml-text = { workspace = true }
tombi-toml-version = { workspace = true }
tower-lsp = { workspace = true, optional = true }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
serde_json = { workspace = true }
test-lib = { workspace = true }
textwrap = { workspace = true }

[features]
default = ["serde"]
lsp = ["dep:tower-lsp", "tombi-text/lsp"]
serde = ["chrono/serde", "dep:serde", "indexmap/serde"]
