[package]
name = "tombi-json"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
itertools.workspace = true
serde.workspace = true
thiserror.workspace = true
tombi-json-lexer.workspace = true
tombi-json-syntax.workspace = true
tombi-json-value.workspace = true
tombi-text.workspace = true
tracing.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
