[package]
name = "tombi-cargo-extension"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Tombi extension for Cargo.toml"
repository.workspace = true
license.workspace = true

[dependencies]
cargo_metadata.workspace = true
itertools.workspace = true
tombi-ast.workspace = true
tombi-config.workspace = true
tombi-document-tree.workspace = true
tombi-extension.workspace = true
tombi-parser.workspace = true
tombi-text.workspace = true
tower-lsp.workspace = true
tracing.workspace = true
