[package]
name = "tombi-validator"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
itertools.workspace = true
regex.workspace = true
thiserror.workspace = true
tombi-diagnostic.workspace = true
tombi-document-tree.workspace = true
tombi-future.workspace = true
tombi-schema-store.workspace = true
tombi-text.workspace = true
tracing.workspace = true
