[package]
name = "linter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ast.workspace = true
config.workspace = true
diagnostic.workspace = true
parser.workspace = true
schemars.workspace = true
serde.workspace = true
syntax.workspace = true
