[package]
name = "tombi-formatter"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
itertools.workspace = true
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
tokio.workspace = true
tombi-ast.workspace = true
tombi-ast-editor.workspace = true
tombi-config.workspace = true
tombi-diagnostic.workspace = true
tombi-document-tree.workspace = true
tombi-json.workspace = true
tombi-parser.workspace = true
tombi-schema-store.workspace = true
tombi-syntax.workspace = true
tombi-text.workspace = true
tracing.workspace = true
unicode-segmentation.workspace = true
url.workspace = true

[dev-dependencies]
assert_matches.workspace = true
pretty_assertions.workspace = true
rstest.workspace = true
textwrap.workspace = true
tokio = { workspace = true, features = ["macros"] }
tombi-test-lib.workspace = true
tracing-subscriber.workspace = true

[features]
jsonschema = ["dep:schemars", "serde"]
serde = ["dep:serde"]
