[package]
name = "tombi-json-value"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
indexmap.workspace = true
serde = { workspace = true, optional = true }
tracing.workspace = true

[features]
default = ["serde"]
serde = ["dep:serde"]
