[package]
name = "tombi-extension-tombi"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
tombi-config.workspace = true
tombi-document-tree.workspace = true
tombi-extension.workspace = true
tombi-schema-store.workspace = true
tombi-text.workspace = true
tower-lsp.workspace = true
tracing.workspace = true
