[package]
name = "tombi-extension-cargo"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Tombi extension for Cargo.toml"
repository.workspace = true
license.workspace = true

[dependencies]
ahash.workspace = true
glob.workspace = true
itertools.workspace = true
serde.workspace = true
serde_json.workspace = true
tombi-ast.workspace = true
tombi-config.workspace = true
tombi-document-tree.workspace = true
tombi-extension.workspace = true
tombi-parser.workspace = true
tombi-schema-store.workspace = true
tombi-text.workspace = true
tombi-version-sort.workspace = true
tower-lsp.workspace = true
tracing.workspace = true
