[package]
name = "server"
version = "0.0.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[features]
clap = ["dep:clap"]

[dependencies]
ast = { workspace = true }
camino = { workspace = true }
clap = { workspace = true, features = ["derive", "string"], optional = true }
config = { workspace = true, features = ["serde"] }
crossbeam-channel = "0.5.13"
dashmap = { workspace = true }
diagnostic = { workspace = true }
document = { workspace = true }
document-tree.workspace = true
formatter = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
linter = { workspace = true }
parser = { workspace = true }
rustc-hash = { workspace = true }
semver = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
text = { workspace = true, features = ["lsp"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["io-std", "rt"] }
tower-lsp = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
rstest.workspace = true
