[package]
name = "server"
version = "0.0.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }

[features]
default = ["clap"]
clap = ["dep:clap"]

[dependencies]
ast = { workspace = true }
camino = { workspace = true }
clap = { workspace = true, optional = true }
config = { workspace = true }
crossbeam-channel = "0.5.13"
dashmap = { workspace = true }
diagnostic = { workspace = true }
document = { workspace = true }
document-tree = { workspace = true }
formatter = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
schema-store = { workspace = true }
linter = { workspace = true }
parser = { workspace = true }
rustc-hash = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
text = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower-lsp = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
syntax.workspace = true
ahash.workspace = true
chrono.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
rstest = { workspace = true }
